services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      - 'POSTGRES_DB=audit'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - 'spring.datasource.url=jdbc:postgresql://postgres/audit'
      - 'spring.datasource.username=postgres'
      - 'spring.datasource.password=postgres'
