CREATE TABLE customers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    email_address VARCHAR(255),
    CONSTRAINT pk_customers PRIMARY KEY (id)
);